Fixup "tk_tcl" build
Explicitly list "srcs" of libtommath instead of "exclude".

Fixes:

libexternal_Stk_Utcl_Slibtcl.so: error: undefined reference to 's_mp_exptmod'
libexternal_Stk_Utcl_Slibtcl.so: error: undefined reference to 's_mp_exptmod_fast'