org_gnu_gnulib: backport coreutils/gnulib@f9e2b20a12
The following error occured on systems with glibc 2.34+:

```
external/org_gnu_gnulib/lib/c-stack.c:55:26: error: function-like macro 'sysconf' is not defined
                         ^
/usr/include/bits/sigstksz.h:28:19: note: expanded from macro 'SIGSTKSZ'
                  ^
external/org_gnu_gnulib/lib/c-stack.c:141:8: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
  char buffer[SIGSTKSZ];
```

It turns out "MINSIGSTKSZ and SIGSTKSZ are no longer constant on
Linux, MINSIGSTKSZ is redefined to sysconf(_SC_MINSIGSTKSZ) and
SIGSTKSZ is redefined to sysconf (_SC_SIGSTKSZ)" [1].

This creates an issue for cases where constant value is expected, but
luckily, upstream already has a patch (coreutils/gnulib@f9e2b20a12).

This change backports the patch to our version of gnulib.

[1]: https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html