Add GitHub source for org_lzma_lzma http_archive.
The Fedora URL is sometimes flaky and causes download errors when fetching the dependency for boost.

Example errors:

https://github.com/google/xls/issues/3254

```
ERROR: /home/testing/.cache/bazel/_bazel_testing/5eeddc84bceff4fbe76fd8c516cb1790/external/bazel_tools/tools/build_defs/repo/http.bzl:136:45: An error occurred during the fetch of repository 'org_lzma_lzma':
   Traceback (most recent call last):
	File "/home/testing/.cache/bazel/_bazel_testing/5eeddc84bceff4fbe76fd8c516cb1790/external/bazel_tools/tools/build_defs/repo/http.bzl", line 136, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://src.fedoraproject.org/lookaside/extras/xz/xz-5.4.6.tar.gz/sha512/b08a61d8d478d3b4675cb1ddacdbbd98dc6941a55bcdd81a28679e54e9367d3a595fa123ac97874a17da571c1b712e2a3e901c2737099a9d268616a1ba3de497/xz-5.4.6.tar.gz] to /home/testing/.cache/bazel/_bazel_testing/5eeddc84bceff4fbe76fd8c516cb1790/external/org_lzma_lzma/temp214682858572773859/xz-5.4.6.tar.gz: Connect timed out
```