Add `mmap.mmap` as argument type.
Fixes;
```
ERROR: /XXXX/pdk/liberty/BUILD:19:21: Checking Python types for pdk/liberty/combine_liberty.py failed: (Exit 1)
pytype.par failed: error executing PytypeCheck command (from target pdk/liberty:combine_liberty@pytype@check) tools/python/pytype/pytype.par --strict-none-binding --use-enum-overlay --check --touch ... (remaining 13 arguments skipped).  [forge_remote_host=jabdj1]
File "pdk/liberty/combine_liberty.py", line 61, in main: Function pdk.liberty.liberty_utility.generate_merged_liberty_io_vector was called with the wrong arguments [wrong-arg-types]
         Expected: (liberty_files: List[bytes])
  Actually passed: (liberty_files: List[mmap.mmap])
```

Signed-off-by: Tim 'mithro' Ansell <me@mith.ro>